### ISSUE TITLE
build log errors

### ISSUE THREAD

**Issue by nsheff** [refgenie/refgenie#164]
I found some errors in the build logs, for example: 

http://refgenomes.databio.org/v2/asset/hg38/bowtie2_index/log?tag=default

```


> `touch /project/shefflab/genomes_parallel/hg38/bismark_bt2_index/default/_refgenie_build/hg38_bismark_bt2_index__default.flag` (14477)
<pre>
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
</pre>
Command completed. Elapsed time: 0:00:01. Running peak memory: 10.804GB.  
  PID: 14477;	Command: touch;	Return code: 0;	Memory used: 0.002GB

shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory

> `cd /project/shefflab/genomes_parallel/hg38/bismark_bt2_index/default; find . -type f -not -path './_refgenie_build*' -exec md5sum {} \; | sort -k 2 | awk '{print $1}' | md5sum`
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Default tag for 'hg38/bismark_bt2_index' set to: default
```

and

```
Traceback (most recent call last):
  File "/home/mjs5kd/.local/bin/refgenie", line 11, in <module>
    sys.exit(main())
  File "/home/mjs5kd/.local/lib/python3.6/site-packages/refgenie/refgenie.py", line 635, in main
    refgenie_build(gencfg, asset_list[0]["genome"], asset_list, args)
  File "/home/mjs5kd/.local/lib/python3.6/site-packages/refgenie/refgenie.py", line 459, in refgenie_build
    if not build_asset(genome, asset_key, asset_tag, asset_build_package, genome_outfolder, specific_args, **input_assets):
  File "/home/mjs5kd/.local/lib/python3.6/site-packages/refgenie/refgenie.py", line 368, in build_asset
    pm = pypiper.PipelineManager(name="refgenie", outfolder=log_outfolder, args=args)
  File "/home/mjs5kd/.local/lib/python3.6/site-packages/pypiper/manager.py", line 293, in __init__
    self.start_pipeline(args, multi)
  File "/home/mjs5kd/.local/lib/python3.6/site-packages/pypiper/manager.py", line 483, in start_pipeline
    self.info("* " + "Working dir".rjust(20) + ":  " + os.getcwd())
FileNotFoundError: [Errno 2] No such file or directory
```

Can you go through the build logs to make sure there are no errors? I am not sure if you can make sense of these errors easily.

**Comment by stolarczyk** [comment]
the errors are related to other asset builds. The loggs appending i multi-asset builds was already raised in #130  and I wasn't sure how to solve it ever since
