### ISSUE TITLE
Don't lock the config if performing read-only operations

### ISSUE THREAD

**Issue by natefoo** [refgenie/refgenie#194]
Would this be possible? For example, because CVMFS is a read-only filesystem (except when working in a transaction), even doing a `refgenie list` fails when the config is in CVMFS:

```pytb
Traceback (most recent call last):
  File "/home/refgenie/refgenie/bin/refgenie", line 33, in <module>
    sys.exit(load_entry_point('refgenie==0.9.3', 'console_scripts', 'refgenie')())
  File "/home/refgenie/refgenie/lib64/python3.6/site-packages/refgenie/refgenie.py", line 697, in main
    rgc = RefGenConf(filepath=gencfg, writable=False)
  File "/home/refgenie/refgenie/lib64/python3.6/site-packages/refgenconf/refgenconf.py", line 75, in __init__
    skip_read_lock=skip_read_lock)
  File "/home/refgenie/refgenie/lib64/python3.6/site-packages/yacman/yacman.py", line 75, in __init__
    create_lock(filepath, wait_max)
  File "/home/refgenie/refgenie/lib64/python3.6/site-packages/ubiquerg/files.py", line 241, in create_lock
    _create_lock(lock_path, filepath, wait_max)
  File "/home/refgenie/refgenie/lib64/python3.6/site-packages/ubiquerg/files.py", line 228, in _create_lock
    raise e
  File "/home/refgenie/refgenie/lib64/python3.6/site-packages/ubiquerg/files.py", line 210, in _create_lock
    create_file_racefree(lock_path)
  File "/home/refgenie/refgenie/lib64/python3.6/site-packages/ubiquerg/files.py", line 173, in create_file_racefree
    fd = os.open(file, write_lock_flags)
OSError: [Errno 30] Read-only file system: '/cvmfs/refgenomes-databio.galaxyproject.org/lock.genomes_config.yaml'
```

**Comment by stolarczyk** [comment]
There's a dedicated option in the `RefGenConf` constructor `skip_read_lock`. Is that what you're looking for?

**Comment by stolarczyk** [comment]
oh, I now I see that you're using the CLI. We'd need to add a CLI hook to skip the lock.

**Comment by nsheff** [comment]
do you think we could somehow detect if it's a RO filesystem and default to not locking in that case? is that a good idea?

**Comment by natefoo** [comment]
If you wrap the open in a try/except and catch `OSError.errno == errno.EROFS` that should do it. Can't speak to whether it's a good idea, though.

**Comment by stolarczyk** [comment]
I think this is a good idea. The point of the lock is to make sure nothing is writing to the config while it's being read. On RO that's inherently solved, right?

**Comment by nsheff** [comment]
yes, but... I'm hesitant because, what if.... the config file is RO, and then you check it, set to skip checks, and then it gets changed to RW.

This wouldn't happen on a file system that's inherently RO, but I'm just not sure it's possible to tell the difference between a filesystem that's always RO, and this particular file being RO at this particular moment --which could change.

That said, this seems like it is super unlikely to come up so I'm fine with going with that as the default, as long as it can be overridden by forcing it.
