### ISSUE TITLE
error with dev digest calculation

### ISSUE THREAD

**Issue by nsheff** [refgenie/refgenie#200]
```
refgenie --version
refgenie 0.10.0-dev
```

Not sure why this doesn't work...

```
bulker run databio/refgenie:0.7.6 refgenie build Aureococcus_anophagefferens_JGI_1_0/fasta --genome-description 'Aureococcus anophagefferens JGI 1.0 ' --files fasta=/project/shefflab/www/refgenie_plantref/Aureococcus_anophagefferens_JGI_1_0-fasta-fasta

Bulker config: /project/shefflab/rivanna_config/bulker.yaml
Activating crate: databio/refgenie:0.7.6

Using 'default' as the default tag for 'Aureococcus_anophagefferens_JGI_1_0/fasta'
Recipe validated successfully against a schema: /home/ns5bc/.local/lib/python3.6/site-packages/refgenie/schemas/recipe_schema.yaml
Building 'Aureococcus_anophagefferens_JGI_1_0/fasta:default' using 'fasta' recipe
Initializing genome: Aureococcus_anophagefferens_JGI_1_0
Traceback (most recent call last):
  File "/home/ns5bc/.local/bin/refgenie", line 10, in <module>
    sys.exit(main())
  File "/home/ns5bc/.local/lib/python3.6/site-packages/refgenie/refgenie.py", line 705, in main
    refgenie_build(gencfg, asset_list[0]["genome"], asset_list, recipe_name, args)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/refgenie/refgenie.py", line 536, in refgenie_build
    alias=ori_genome)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/refgenconf/refgenconf.py", line 1330, in initialize_genome
    asdl = ssc.retrieve(druid=d, reclimit=1)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/refgenconf/henge.py", line 149, in retrieve
    return reconstruct_item(string, schema, reclimit)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/refgenconf/henge.py", line 102, in reconstruct_item
    substr in string.split(DELIM_ITEM)]
  File "/home/ns5bc/.local/lib/python3.6/site-packages/refgenconf/henge.py", line 102, in <listcomp>
    substr in string.split(DELIM_ITEM)]
  File "/home/ns5bc/.local/lib/python3.6/site-packages/refgenconf/henge.py", line 130, in reconstruct_item
    return self.retrieve(string, reclimit, raw)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/refgenconf/henge.py", line 137, in retrieve
    raise NotFoundException(druid)
refgenconf.henge.NotFoundException:  not found in database
```

The first time I ran it, got this error:

```
Initializing genome: Aureococcus_anophagefferens_JGI_1_0                                                                           
Traceback (most recent call last):                                                                                                 
  File "/home/ns5bc/.local/bin/refgenie", line 10, in <module>                                                                     
    sys.exit(main())                                                                                                               
  File "/home/ns5bc/.local/lib/python3.6/site-packages/refgenie/refgenie.py", line 705, in main                                    
    refgenie_build(gencfg, asset_list[0]["genome"], asset_list, recipe_name, args)                                                 
  File "/home/ns5bc/.local/lib/python3.6/site-packages/refgenie/refgenie.py", line 536, in refgenie_build                          
    alias=ori_genome)                                                                                                              
  File "/home/ns5bc/.local/lib/python3.6/site-packages/refgenconf/refgenconf.py", line 1328, in initialize_genome                  
    d, _ = ssc.load_fasta(fasta_path)                                                                                              
  File "/home/ns5bc/.local/lib/python3.6/site-packages/refgenconf/seqcol.py", line 109, in load_fasta                              
    fa_object = parse_fasta(fa_file)                                                                                               
  File "/home/ns5bc/.local/lib/python3.6/site-packages/refgenconf/seqcol.py", line 238, in parse_fasta                             
    return pyfaidx.Fasta(fa_file)                                                                                                  
  File "/home/ns5bc/.local/lib/python3.6/site-packages/pyfaidx/__init__.py", line 999, in __init__                                 
    build_index=build_index)                                                                                                       
  File "/home/ns5bc/.local/lib/python3.6/site-packages/pyfaidx/__init__.py", line 423, in __init__                                 
    self.build_index()                                                                                                             
  File "/home/ns5bc/.local/lib/python3.6/site-packages/pyfaidx/__init__.py", line 519, in build_index                              
    line = line.decode()                                                                                                           
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte 
```

now every time I run it, I get the first error

**Comment by nsheff** [comment]
updated to the latest commit from today the line numbers chagne slightly:
```
Using 'default' as the default tag for 'Aureococcus_anophagefferens_JGI_1_0/fasta'
Recipe validated successfully against a schema: /home/ns5bc/.local/lib/python3.6/site-packages/refgenie/schemas/recipe_schema.yaml
Building 'Aureococcus_anophagefferens_JGI_1_0/fasta:default' using 'fasta' recipe
Initializing genome: Aureococcus_anophagefferens_JGI_1_0
Traceback (most recent call last):
  File "/home/ns5bc/.local/bin/refgenie", line 10, in <module>
    sys.exit(main())
  File "/home/ns5bc/.local/lib/python3.6/site-packages/refgenie/refgenie.py", line 713, in main
    refgenie_build(gencfg, asset_list[0]["genome"], asset_list, recipe_name, args)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/refgenie/refgenie.py", line 543, in refgenie_build
    alias=ori_genome)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/refgenconf/refgenconf.py", line 1330, in initialize_genome
    asdl = ssc.retrieve(druid=d, reclimit=1)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/refgenconf/henge.py", line 149, in retrieve
    return reconstruct_item(string, schema, reclimit)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/refgenconf/henge.py", line 102, in reconstruct_item
    substr in string.split(DELIM_ITEM)]
  File "/home/ns5bc/.local/lib/python3.6/site-packages/refgenconf/henge.py", line 102, in <listcomp>
    substr in string.split(DELIM_ITEM)]
  File "/home/ns5bc/.local/lib/python3.6/site-packages/refgenconf/henge.py", line 130, in reconstruct_item
    return self.retrieve(string, reclimit, raw)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/refgenconf/henge.py", line 137, in retrieve
    raise NotFoundException(druid)
refgenconf.henge.NotFoundException:  not found in database
```

**Comment by nsheff** [comment]
is it expecting a non-gzipped fasta file? but doesn't the recipe expect a gzipped fasta file?

**Comment by stolarczyk** [comment]
I'm investigating this now. Were you able to build any other fasta asset? I haven't seen this error before even though I've build couple of them.

**Comment by nsheff** [comment]
it should handle both a zipped file and a non-zipped file. This is the first one I tried, I haven't successfully built any. I'm also investigating.

**Comment by nsheff** [comment]
I wonder if the file extension is the problem.

**Comment by nsheff** [comment]
Look:


```
ssc =  refgenconf.seqcol.SeqColClient({})
ssc.load_fasta("/project/shefflab/www/refgenie_plantref/Aureococcus_anophagefferens_JGI_1_0-fasta-fasta")                  
Out[7]: ('cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc', [])                                                                   
                                                                                                                                   
In [8]: x = ssc.load_fasta("/project/shefflab/www/refgenie_plantref/Aureococcus_anophagefferens_JGI_1_0-fasta-fasta")              
                                                                                                                                   
In [9]: ssc.retrieve(x[0])      
---------------------------------------------------------------------------
NotFoundException                         Traceback (most recent call last)
<ipython-input-9-88bcfdbe5931> in <module>
----> 1 ssc.retrieve(x[0])

~/.local/lib/python3.6/site-packages/refgenconf/henge.py in retrieve(self, druid, reclimit, raw)
    147 
    148         schema = self.schemas[item_type]
--> 149         return reconstruct_item(string, schema, reclimit)
    150 
    151     @property

~/.local/lib/python3.6/site-packages/refgenconf/henge.py in reconstruct_item(string, schema, reclimit)
    100             if "type" in schema and schema["type"] == "array":
    101                 return [reconstruct_item(substr, schema["items"], reclimit) for
--> 102                         substr in string.split(DELIM_ITEM)]
    103             elif schema["type"] == "object":
    104                 # else:  # assume it's an object

~/.local/lib/python3.6/site-packages/refgenconf/henge.py in <listcomp>(.0)
    100             if "type" in schema and schema["type"] == "array":
    101                 return [reconstruct_item(substr, schema["items"], reclimit) for
--> 102                         substr in string.split(DELIM_ITEM)]
    103             elif schema["type"] == "object":
    104                 # else:  # assume it's an object

~/.local/lib/python3.6/site-packages/refgenconf/henge.py in reconstruct_item(string, schema, reclimit)
    128                         if isinstance(reclimit, int):
    129                             reclimit = reclimit - 1
--> 130                         return self.retrieve(string, reclimit, raw)
    131                 else:
    132                     print("not recursive")

~/.local/lib/python3.6/site-packages/refgenconf/henge.py in retrieve(self, druid, reclimit, raw)
    135 
    136         if not druid + ITEM_TYPE in self.database:
--> 137             raise NotFoundException(druid)
    138 
    139         item_type = self.database[druid + ITEM_TYPE]

NotFoundException:  not found in database
```

```ssc.show()             
('cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc', '')
('cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc_item_type', 'AnnotatedSequenceList')
('cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc_digest_version', 'md5')
```

**Comment by stolarczyk** [comment]
it's the extension:

```
[mstolarczyk@MichalsMBP r_compat]: cp t7.fa.gz t7-fasta
```
```
[mstolarczyk@MichalsMBP r_compat]: refgenie build -c g.yml t7/fasta --files fasta=t7-fasta 
Using 'default' as the default tag for 't7/fasta'
Recipe validated successfully against a schema: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/refgenie/schemas/recipe_schema.yaml
Building 't7/fasta:default' using 'fasta' recipe
Initializing genome: t7
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/refgenie", line 10, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/refgenie/refgenie.py", line 715, in main
    refgenie_build(gencfg, asset_list[0]["genome"], asset_list, recipe_name, args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/refgenie/refgenie.py", line 545, in refgenie_build
    alias=ori_genome)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/refgenconf/refgenconf.py", line 1334, in initialize_genome
    d, _ = ssc.load_fasta(fasta_path)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/refgenconf/seqcol.py", line 109, in load_fasta
    fa_object = parse_fasta(fa_file)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/refgenconf/seqcol.py", line 238, in parse_fasta
    return pyfaidx.Fasta(fa_file)
  File "/Users/mstolarczyk/Library/Python/3.6/lib/python/site-packages/pyfaidx/__init__.py", line 996, in __init__
    build_index=build_index)
  File "/Users/mstolarczyk/Library/Python/3.6/lib/python/site-packages/pyfaidx/__init__.py", line 423, in __init__
    self.build_index()
  File "/Users/mstolarczyk/Library/Python/3.6/lib/python/site-packages/pyfaidx/__init__.py", line 519, in build_index
    line = line.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
[mstolarczyk@MichalsMBP r_compat]: refgenie build -c g.yml t7/fasta --files fasta=t7-fasta 
Using 'default' as the default tag for 't7/fasta'
Recipe validated successfully against a schema: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/refgenie/schemas/recipe_schema.yaml
Building 't7/fasta:default' using 'fasta' recipe
Initializing genome: t7
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/refgenie", line 10, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/refgenie/refgenie.py", line 715, in main
    refgenie_build(gencfg, asset_list[0]["genome"], asset_list, recipe_name, args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/refgenie/refgenie.py", line 545, in refgenie_build
    alias=ori_genome)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/refgenconf/refgenconf.py", line 1336, in initialize_genome
    asdl = ssc.retrieve(druid=d, reclimit=1)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/refgenconf/henge.py", line 149, in retrieve
    return reconstruct_item(string, schema, reclimit)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/refgenconf/henge.py", line 102, in reconstruct_item
    substr in string.split(DELIM_ITEM)]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/refgenconf/henge.py", line 102, in <listcomp>
    substr in string.split(DELIM_ITEM)]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/refgenconf/henge.py", line 130, in reconstruct_item
    return self.retrieve(string, reclimit, raw)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/refgenconf/henge.py", line 137, in retrieve
    raise NotFoundException(druid)
refgenconf.henge.NotFoundException:  not found in database
```

**Comment by nsheff** [comment]
but that item *is* in the database, you can see it with `.show`!

**Comment by nsheff** [comment]
can you explain why the error is different on the first vs subsequent trials? The database doesn't persist, does it?

**Comment by stolarczyk** [comment]
The error is different because the `pyfaidx.Fasta` method behaves unexpectedly. It tries to read the compressed FASTA file in, and at first it raises an error, then it "succeeds":

```
[mstolarczyk@MichalsMBP r_compat]: cp t7.fa.gz t7-gzipped-noext
```
```
[mstolarczyk@MichalsMBP r_compat]: ipy
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 05:52:31) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.5.0 -- An enhanced Interactive Python. Type '?' for help.

autoreload startup script has been executed!

In [1]: import pyfaidx                                                                                                                                                                                    

In [2]: x=pyfaidx.Fasta("t7-gzipped-noext")                                                                                                                                                               
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-2-271b6bac7783> in <module>
----> 1 x=pyfaidx.Fasta("t7-gzipped-noext")

~/Library/Python/3.6/lib/python/site-packages/pyfaidx/__init__.py in __init__(self, filename, default_seq, key_function, as_raw, strict_bounds, read_ahead, mutable, split_char, filt_function, one_based_attributes, read_long_names, duplicate_action, sequence_always_upper, rebuild, build_index)
    994             sequence_always_upper=sequence_always_upper,
    995             rebuild=rebuild,
--> 996             build_index=build_index)
    997         self.keys = self.faidx.index.keys
    998         if not self.mutable:

~/Library/Python/3.6/lib/python/site-packages/pyfaidx/__init__.py in __init__(self, filename, default_seq, key_function, as_raw, strict_bounds, read_ahead, mutable, split_char, duplicate_action, filt_function, one_based_attributes, read_long_names, sequence_always_upper, rebuild, build_index)
    421                             self.indexname, self.filename), RuntimeWarning)
    422                 elif build_index:
--> 423                     self.build_index()
    424                     self.read_fai()
    425                 else:

~/Library/Python/3.6/lib/python/site-packages/pyfaidx/__init__.py in build_index(self)
    517                     for i, line in enumerate(fastafile):
    518                         line_blen = len(line)
--> 519                         line = line.decode()
    520                         line_clen = len(line.rstrip('\n\r'))
    521                         lastline = i

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

In [3]: x=pyfaidx.Fasta("t7-gzipped-noext")  
```

**Comment by stolarczyk** [comment]
so I think a possible solution is to handle the format detection on our own and make sure we feed an uncompressed FASTA file to `pyfaidx.Fasta`

**Comment by nsheff** [comment]
we want to be able to feed a compressed one to it, though.

**Comment by stolarczyk** [comment]
yes, our `parse_fasta` function takes care of unzipping the FASTA file, but we depend on exceptions raised by `pyfaidx.Fasta` to determine if we need to unzip it. It just needs to happen first, if needed. Then we can pass an unzipped FASTA .

**Comment by nsheff** [comment]
how about this? https://github.com/refgenie/refgenconf/pull/104
we know the input is gzipped so we can just set it.

**Comment by stolarczyk** [comment]
yes, that worked for me as well.
