### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by nsheff** [refgenie/refgenie#201]
My second sample yields this error now:

```
## [2 of 156] sample: Asterochloris_sp__Cgr/DA1pho_v2_0_JGI_7_45_13-fasta; pipeline: refgenie
Could not write sample data to: /project/shefflab//deploy/plantref/genomes/submission/Asterochloris_sp__Cgr/DA1pho_v2_0_JGI_7_45_13
-fasta.yaml. Directory does not exist
Writing script to /project/shefflab/deploy/plantref/genomes/submission/refgenie_Asterochloris_sp__Cgr/DA1pho_v2_0_JGI_7_45_13-fasta
.sub
Job script (n=1; 0.00Gb): /project/shefflab//deploy/plantref/genomes/submission/refgenie_Asterochloris_sp__Cgr/DA1pho_v2_0_JGI_7_45
_13-fasta.sub
Compute node: udc-ba36-36
Start time: 2020-08-24 13:12:18
Bulker config: /project/shefflab/rivanna_config/bulker.yaml
Activating crate: databio/refgenie:0.7.6

Traceback (most recent call last):
  File "/home/ns5bc/.local/bin/refgenie", line 10, in <module>
    sys.exit(main())
  File "/home/ns5bc/.local/lib/python3.6/site-packages/refgenie/refgenie.py", line 648, in main
    if not a["genome"]:
TypeError: 'NoneType' object is not subscriptable
```

**Comment by stolarczyk** [comment]
in `/project/shefflab//deploy/plantref/genomes/submission/refgenie_Asterochloris_sp__Cgr/DA1pho_v2_0_JGI_7_45_13-fasta.sub` the asset registry path is invalid: Asterochloris_sp__Cgr/DA1pho_v2_0_JGI_7_45_13/fasta

**Comment by nsheff** [comment]
yeah, it's a slash in the name of the genome.

**Comment by nsheff** [comment]
maybe we can do a better job of catching this somewhere?

**Comment by stolarczyk** [comment]
we could add a constraint in a asset PEP schema for example
