### ISSUE TITLE
missing data folder

### ISSUE THREAD

**Issue by nsheff** [refgenie/refgenie#208]
does the user have to manually create a `data` folder under the new config format? should this be created by `init` ?

```
refgenie init -c $REFGENIE
Initialized genome configuration file: /home/nsheff/garage/refgenie/refgenie_v4.yaml
```

now pull something:
```
databio/methpl|~/garage/refgenie$ refgenie pull t7/fasta
Traceback (most recent call last):
  File "/home/nsheff/.local/bin/refgenie", line 8, in <module>
    sys.exit(main())
  File "/home/nsheff/.local/lib/python3.8/site-packages/refgenie/refgenie.py", line 761, in main
    raise MissingFolderError(outdir)
refgenie.exceptions.MissingFolderError: /home/nsheff/garage/refgenie/data
```

**Comment by stolarczyk** [comment]
yes, you're right. I've never pulled an asset _first_ after the updates so I didn't catch that..
