### ISSUE TITLE
alias error

### ISSUE THREAD

**Issue by nsheff** [refgenie/refgenie#221]
```
refgenie alias
Traceback (most recent call last):
  File "/home/ns5bc/.local/bin/refgenie", line 10, in <module>
    sys.exit(main())
  File "/home/ns5bc/.local/lib/python3.6/site-packages/refgenie/refgenie.py", line 673, in main
    filename=args.genome_config, check_exist=not args.command == INIT_CMD,
AttributeError: 'Namespace' object has no attribute 'genome_config'
```

**Comment by stolarczyk** [comment]
that's an argument parser issue `refgenie alias get` works. The path to the file from the env var is not passed correctly.

**Comment by nsheff** [comment]
yeah, I was expecting `refgenie alias` to just yield the help menu

**Comment by nsheff** [comment]
Related to #222
