### ISSUE TITLE
init error

### ISSUE THREAD

**Issue by nsheff** [refgenie/refgenie#236]
```
refgenie init -c config/refgenie_config.yaml -f $GENOMES -u http://awspds.refgenie.databio.org/refgenomes.databio.org/ -a $GENOMES/archive -b refgenie_config_archive.yaml
RefGenConf object did not pass schema validation
Traceback (most recent call last):
  File "/home/ns5bc/.local/bin/refgenie", line 10, in <module>
    sys.exit(main())
  File "/home/ns5bc/.local/lib/python3.6/site-packages/refgenie/refgenie.py", line 738, in main
    rgc = RefGenConf(entries=entries, skip_read_lock=skip_read_lock)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/refgenconf/refgenconf.py", line 108, in __init__
    write_validate=True,
  File "/home/ns5bc/.local/lib/python3.6/site-packages/yacman/yacman.py", line 141, in __init__
    self.validate()
  File "/home/ns5bc/.local/lib/python3.6/site-packages/yacman/yacman.py", line 199, in validate
    self.to_dict(expand=True), schema or getattr(self[IK], SCHEMA_KEY)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/jsonschema/validators.py", line 934, in validate
    raise error
jsonschema.exceptions.ValidationError: 'http://refgenomes.databio.org' is not of type 'array'

Failed validating 'type' in schema['properties']['genome_servers']:
    {'items': {'type': 'string'}, 'type': 'array'}

On instance['genome_servers']:
    'http://refgenomes.databio.org'
```

**Comment by nsheff** [comment]
can't figure out why I can't `init` a new config...

**Comment by stolarczyk** [comment]
The error message says that the schema expects the genome_servers to be an array of strings. You used a single string.

**Comment by nsheff** [comment]
is this related to pending changes in the genome_servers attribute?

**Comment by nsheff** [comment]
It has always worked like that... I'm just copying code from a tutorial

**Comment by stolarczyk** [comment]
Will need to update the schema to accommodate single strings as well

**Comment by nsheff** [comment]
I also didn't pass that string. it didn't come from my command.

**Comment by nsheff** [comment]
it's coming from the default to `-s` in `refgenie init`, which is a string.  it's hard to pass an array on the CLI, btw

**Comment by nsheff** [comment]
Interesting... this works:

```
refgenie init -c config/refgenie_config2.yaml -f $GENOMES -u http://awspds.refgenie.databio.org/refgenomes.databio.org/ -a $GENOMES/archive -b refgenie_config_archive.yaml -s http://refgenomes.databio.org
```

This doesnT:
```
refgenie init -c config/refgenie_config2.yaml -f $GENOMES -u http://awspds.refgenie.databio.org/refgenomes.databio.org/ -a $GENOMES/archive -b refgenie_config_archive.yaml 
```

**Comment by stolarczyk** [comment]
Yes, forcing users to pass an array in every case is not the solution here. The schema has to accept both classes.

**Comment by nsheff** [comment]
But passing a string on the CLI actually worked. it's just something to do with the default argparser that breaks it.

**Comment by stolarczyk** [comment]
Just ran the exact command you pasted and it worked fine:

```
~ refgenie init -c config/refgenie_config.yaml -f $GENOMES -u http://awspds.refgenie.databio.org/refgenomes.databio.org/ -a $GENOMES/archive -b refgenie_config_archive.yaml

Initialized genome configuration file: /Users/mstolarczyk/Desktop/testing/refgenie/config/refgenie_config.yaml
Created directories:
 - /Users/mstolarczyk/code/genomes/data
 - /Users/mstolarczyk/code/genomes/alias
 ```

The argparser's default looks correct, too:

```python
    sps[INIT_CMD].add_argument(
        "-s",
        "--genome-server",
        nargs="+",
        default=[DEFAULT_SERVER],
        help=f"URL(s) to use for the {CFG_SERVERS_KEY} attribute in config file. Default: {DEFAULT_SERVER}.",
    )
```

it's an array of strings

I'm using current dev versions of refgnie and refgenconf

**Comment by nsheff** [comment]
Ok I'll double-check. I was using dev refgenconf but it may have been a few commits old.
