### ISSUE TITLE
regenie pull Error

### ISSUE THREAD

**Issue by arpanda** [refgenie/refgenie#246]
Hi, 
I was trying to pull an asset but getting error. I have used the below command:
```
refgenie pull hg38/bowtie2_index
```

Here is the last three  line of the error:
```
File "/usr/local/biotools/python/python-3.7.6/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I have used it earlier. It was working fine. Not sure what happened. Any suggestions?

**Comment by nsheff** [comment]
can you show us your refgenie configuration file? It looks like an empty file?

**Comment by arpanda** [comment]
I am using Python 3.7.10. and here is the version refgenie details.
```
refgenie --version
refgenie 0.10.0 | refgenconf 0.10.0
```

Here is the configuration file

```
config_version: 0.4
genome_folder: <data_path>/data/refgenie_data
genome_servers:
 - http://refgenomes.databio.org
genomes:
....
```

**Comment by stolarczyk** [comment]
I have just pulled an asset using the same version of refgenie and refgenconf but with Python 3.9, so I wasn't able to reproduce this error.

For the config file, the part of interest is the `genomes` section which you skipped. 

A couple of things so we can move further:

1. Paste the `refgenie pull` log
2. Paste the entire config file

**Comment by arpanda** [comment]
I thought, you wanted the check the server and config details. Anyway, here is the entire config file. 
```
config_version: 0.4
genome_folder: <data_path>/data/refgenie_data
genome_servers:
 - http://refgenomes.databio.org
genomes:
  2230c535660fb4774114bfa966a62f823fdb6d21acf138d4:
    aliases:
     - hg38
    assets:
      fasta:
        tags:
          default:
            seek_keys:
              fasta: 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4.fa
              fai: 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4.fa.fai
              chrom_sizes: 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4.chrom.sizes
            asset_parents: []
            asset_path: fasta
            asset_digest: 59fed5ec3c3a95bc5709b24b8f2cf7bf
            asset_children:
             - 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4/bowtie2_index:default
        default_tag: default
      bowtie2_index:
        tags:
          default:
            seek_keys:
              bowtie2_index: 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4
            asset_parents:
             - 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4/fasta:default
            asset_path: bowtie2_index
            asset_digest: 04880a3192a69bbfdc36da25b67203cb
        default_tag: default
      refgene_anno:
        tags:
          default:
            seek_keys:
              refgene_anno: 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4_refGene.txt.gz
              refgene_tss: 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4_TSS.bed
              refgene_exon: 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4_exons.bed
              refgene_intron: 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4_introns.bed
              refgene_pre_mRNA: 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4_pre-mRNA.bed
            asset_parents: []
            asset_path: refgene_anno
            asset_digest: 4d0ff5d90ac529a4fffdd5704d8ec6d9
        default_tag: default
      ensembl_gtf:
        tags:
          default:
            asset_digest: 247fa6fbf98ce6b5773cbed0bdd86fef
            asset_children:
             - 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4/feat_annotation:default
            seek_keys:
              ensembl_gtf: 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4.gtf.gz
              ensembl_tss: 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4_ensembl_TSS.bed
              ensembl_gene_body: 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4_ensembl_gene_body.bed
            asset_parents: []
            asset_path: ensembl_gtf
        default_tag: default
      ensembl_rb:
        tags:
          default:
            asset_digest: d743c316efe1e13ce8a2546fbe3adf69
            asset_children:
             - 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4/feat_annotation:default
      feat_annotation:
        tags:
          default:
            seek_keys:
              feat_annotation: 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4_annotations.bed.gz
            asset_parents:
             - 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4/ensembl_gtf:default
             - 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4/ensembl_rb:default
            asset_path: feat_annotation
            asset_digest: 3549873db4390b9643173b134837d497
        default_tag: default
      gencode_gtf:
        tags:
          default:
            seek_keys:
              gencode_gtf: 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4.gtf.gz
            asset_parents: []
            asset_path: gencode_gtf
            asset_digest: 55cad7e24235fa842628a3c1f9542c1f
        default_tag: default
    genome_description: The GCA_000001405.15 GRCh38_no_alt_analysis_set from NCBI
```

Here is the log for `refgenie pull hg19/fasta`.
```
Compatible refgenieserver instances: ['http://refgenomes.databio.org']
No local digest for genome alias: hg19
Setting 'hg19' identity with server: http://refgenomes.databio.org/v3/genomes/genome_digest/hg19
Traceback (most recent call last):
  File "<data_path>/.local/lib/python3.7/site-packages/refgenconf/refgenconf.py", line 1400, in pull
    genome = self.get_genome_alias_digest(alias=alias)
  File "<data_path>/.local/lib/python3.7/site-packages/refgenconf/refgenconf.py", line 1621, in get_genome_alias_digest
    return self[CFG_GENOMES_KEY].get_key(alias=alias)
  File "<data_path>/.local/lib/python3.7/site-packages/yacman/alias.py", line 223, in get_key
    raise UndefinedAliasError("No key defined for: {}".format(alias))
yacman.exceptions.UndefinedAliasError: No key defined for: hg19

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<data_path>/bin/refgenie", line 8, in <module>
    sys.exit(main())
  File "<data_path>/.local/lib/python3.7/site-packages/refgenie/cli.py", line 226, in main
    size_cutoff=args.size_cutoff,
  File "<data_path>/.local/lib/python3.7/site-packages/refgenconf/refgenconf.py", line 1404, in pull
    genome=alias, servers=[server_url], create_genome=True
  File "<data_path>/.local/lib/python3.7/site-packages/refgenconf/refgenconf.py", line 1769, in set_genome_alias
    digest = download_json(url_alias)
  File "<data_path>/.local/lib/python3.7/site-packages/refgenconf/helpers.py", line 304, in download_json
    return resp.json()
  File "/usr/local/biotools/python/python-3.7.6/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/biotools/python/python-3.7.6/lib/python3.7/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/biotools/python/python-3.7.6/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/biotools/python/python-3.7.6/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
``` 
Note: I have replaced some of the data path that has some system user info. Hope that is fine to explain the issue

**Comment by stolarczyk** [comment]
Thanks @arpanda. 

I was able to identify the issue, of of the endpoints in the new refgenieserver version is not backwards-compatible with the old refgenconf package due to this change: https://github.com/refgenie/refgenieserver/issues/67

So just upgrade refgenie and refgenconf. The command below should solve it:

```
pip install --upgrade refgenie
```

**Comment by arpanda** [comment]
it solves the issue. Thanks for your quick response.
