### ISSUE TITLE
KeyError: 'aliases'  - problem with concurrency?

### ISSUE THREAD

**Issue by pinin4fjords** [refgenie/refgenie#253]
Hi!

Apologies in advance for the sketchy report, I'm having trouble pinning this down.

I'm trying to build a large number of assets as part of a workflow. There's a bit of parallel building going on, though I've restricted it so it's not 100s or anything. I get occasional errors like:

```
Recipe validated successfully against a schema: /path/to/conda/envs/refgenie-4f835c0534e73b8fd87dac6c443854f1/lib/python3.6/site-packages/refgenie/schemas/recipe_schema.yaml
Building 'phytophthora_kernoviae--PhyKer238_432v1/salmon_index:cdna_protists51--spikes_ercc--salmon_v1.2.0' using 'salmon_index' recipe
Saving outputs to:
- content: /path/to/references/refgenie/data/246991e122049429ee9c6d704bdbbd7e0fa59966c64dccf1
- logs: /path/to/references/refgenie/data/246991e122049429ee9c6d704bdbbd7e0fa59966c64dccf1/salmon_index/cdna_protists51--spikes_ercc--salmon_v1.2.0/_refgenie_build
RefGenConf object did not pass schema validation
Traceback (most recent call last):
  File "/path/to/conda/envs/refgenie-4f835c0534e73b8fd87dac6c443854f1/bin/refgenie", line 10, in <module>
    sys.exit(main())
  File "/path/to/conda/envs/refgenie-4f835c0534e73b8fd87dac6c443854f1/lib/python3.6/site-packages/refgenie/cli.py", line 147, in main
    refgenie_build(gencfg, asset_list[0]["genome"], asset_list, recipe_name, args)
  File "/path/to/conda/envs/refgenie-4f835c0534e73b8fd87dac6c443854f1/lib/python3.6/site-packages/refgenie/refgenie.py", line 107, in refgenie_build
    skip_read_lock=_skip_lock(args.skip_read_lock, gencfg),
  File "/path/to/conda/envs/refgenie-4f835c0534e73b8fd87dac6c443854f1/lib/python3.6/site-packages/refgenconf/refgenconf.py", line 102, in __init__
    write_validate=True,
  File "/path/to/conda/envs/refgenie-4f835c0534e73b8fd87dac6c443854f1/lib/python3.6/site-packages/yacman/yacman.py", line 141, in __init__
    self.validate()
  File "/path/to/conda/envs/refgenie-4f835c0534e73b8fd87dac6c443854f1/lib/python3.6/site-packages/yacman/yacman.py", line 199, in validate
    self.to_dict(expand=True), schema or getattr(self[IK], SCHEMA_KEY)
  File "/path/to/conda/envs/refgenie-4f835c0534e73b8fd87dac6c443854f1/lib/python3.6/site-packages/jsonschema/validators.py", line 934, in validate
    raise error
jsonschema.exceptions.ValidationError: None is not of type 'array'

Failed validating 'type' in schema['properties']['genomes']['patternProperties']['^.*$']['properties']['assets']['patternProperties']['^.*$']['properties']['tags']['patternProperties']['^.*$']['properties']['asset_parents']:
    {'items': {'type': 'string'}, 'type': 'array'}

On instance['genomes']['3ce8a0c0df0512d851c0f38b3657e7daefd957281318b499']['assets']['kallisto_index']['tags']['cdna_fungi43--spikes_ercc--kallisto_v0.45.0']['asset_parents']:
    None
```

(I'm unsure why the kallisto index is mentioned in that trace)

This is stochastic, so I've set the workflow to automatically retry a couple of times. But the retry is producing errors like: 

```
  Recipe validated successfully against a schema: /path/to/conda/envs/refgenie-4f835c0534e73b8fd87dac6c443854f1/lib/python3.6/site-packages/refgenie/schemas/recipe_schema.yaml
  Building 'phytophthora_kernoviae--PhyKer238_432v1/salmon_index:cdna_protists51--spikes_ercc--salmon_v1.2.0' using 'salmon_index' recipe
  Saving outputs to:
  - content: /path/to/references/refgenie/data/246991e122049429ee9c6d704bdbbd7e0fa59966c64dccf1
  - logs: /path/to/references/refgenie/data/246991e122049429ee9c6d704bdbbd7e0fa59966c64dccf1/salmon_index/cdna_protists51--spikes_ercc--salmon_v1.2.0/_refgenie_build
  Traceback (most recent call last):
    File "/path/to/conda/envs/refgenie-4f835c0534e73b8fd87dac6c443854f1/lib/python3.6/site-packages/attmap/ordattmap.py", line 45, in __getitem__
      return super(OrdAttMap, self).__getitem__(item)
  KeyError: 'aliases'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/path/to/conda/envs/refgenie-4f835c0534e73b8fd87dac6c443854f1/lib/python3.6/site-packages/yacman/alias.py", line 76, in __init__
      res = aliases(self)
    File "/path/to/conda/envs/refgenie-4f835c0534e73b8fd87dac6c443854f1/lib/python3.6/site-packages/refgenconf/refgenconf.py", line 180, in <lambda>
      aliases=lambda x: {k: v.__getitem__(CFG_ALIASES_KEY) for k, v in list(x.items())},
    File "/path/to/conda/envs/refgenie-4f835c0534e73b8fd87dac6c443854f1/lib/python3.6/site-packages/refgenconf/refgenconf.py", line 180, in <dictcomp>
      aliases=lambda x: {k: v.__getitem__(CFG_ALIASES_KEY) for k, v in list(x.items())},
    File "/path/to/conda/envs/refgenie-4f835c0534e73b8fd87dac6c443854f1/lib/python3.6/site-packages/attmap/pathex_attmap.py", line 56, in __getitem__
      v = super(PathExAttMap, self).__getitem__(item)
    File "/path/to/conda/envs/refgenie-4f835c0534e73b8fd87dac6c443854f1/lib/python3.6/site-packages/attmap/ordattmap.py", line 47, in __getitem__
      return AttMap.__getitem__(self, item)
    File "/path/to/conda/envs/refgenie-4f835c0534e73b8fd87dac6c443854f1/lib/python3.6/site-packages/attmap/attmap.py", line 32, in __getitem__
      return self.__dict__[item]
  KeyError: 'aliases'
```

When I go and manually trigger the build process a few minutes later, it completes without error. 

Is this maybe an issue with having multiple ongoing build processes?

**Comment by pinin4fjords** [comment]
Note: as a workaround I've added a back-off to the retries which _seems_ to be helping.

**Comment by stolarczyk** [comment]
thanks for reporting. Yes, this might be a concurrency-related issue. But the `None` value in the `asset_parents` section is concerning, which was captured by the config validation.

We will look into this

**Comment by pinin4fjords** [comment]
Here are some high-verbosity logs from an example. 

[stdout.txt](https://github.com/refgenie/refgenie/files/6598863/stdout.txt)
[stderr.txt](https://github.com/refgenie/refgenie/files/6598864/stderr.txt)

**Comment by stolarczyk** [comment]
I think it this further indicates that that's a concurrency issue. The config is in a corrupted state when it is read by the process that produced these logs -- `aliases` section must be present for all genomes.

That said, the problematic piece of code can't be traced by these logs, since it's another process that unlocked the file too early, which might be a bug or just caused by a failure there etc.

Again, backing the `RefGenConf` object by a DB is the way to go.

**Comment by nsheff** [comment]
Related to: https://github.com/refgenie/refgenconf/issues/119
