### ISSUE TITLE
Refgenie pull: Downloaded asset folder is empty

### ISSUE THREAD

**Issue by nich-sugiarto** [refgenie/refgenie#273]
I am trying to initialize hg38 from refgenie. On testing the installation after running the line 
`refgenie pull rCRSd/bowtie2_index`
I get the following output:

```
Compatible refgenieserver instances: ['http://refgenomes.databio.org']
No local digest for genome alias: rCRSd
Setting 'rCRSd' identity with server: http://refgenomes.databio.org/v3/genomes/genome_digest/rCRSd
Determined digest for local 'rCRSd' alias: 94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4
Set genome alias (94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4: rCRSd)
Created alias directories:
 - /dartfs-hpc/rc/lab/W/WangX/Genomes_and_extra/refgenie/alias/rCRSd
Downloading URL: http://refgenomes.databio.org/v3/assets/archive/94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4/bowtie2_index
```

However, when running to run the line
`refgenie seek rCRSd/bowtie2_index`

I get the following error:

```
Using 'default' as the default tag for 'rCRSd/bowtie2_index'
Traceback (most recent call last):
  File "/dartfs-hpc/rc/home/0/f003xn0/.conda/envs/pepatac/lib/python3.9/site-packages/attmap/ordattmap.py", line 46, in __getitem__
    return super(OrdAttMap, self).__getitem__(item)
KeyError: 'assets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dartfs-hpc/rc/home/0/f003xn0/.conda/envs/pepatac/lib/python3.9/site-packages/refgenconf/refgenconf.py", line 2763, in _assert_gat_exists
    asset_data = genome[CFG_ASSETS_KEY][aname]
  File "/dartfs-hpc/rc/home/0/f003xn0/.conda/envs/pepatac/lib/python3.9/site-packages/attmap/pathex_attmap.py", line 59, in __getitem__
    v = super(PathExAttMap, self).__getitem__(item)
  File "/dartfs-hpc/rc/home/0/f003xn0/.conda/envs/pepatac/lib/python3.9/site-packages/attmap/ordattmap.py", line 48, in __getitem__
    return AttMap.__getitem__(self, item)
  File "/dartfs-hpc/rc/home/0/f003xn0/.conda/envs/pepatac/lib/python3.9/site-packages/attmap/attmap.py", line 32, in __getitem__
    return self.__dict__[item]
KeyError: 'assets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dartfs-hpc/rc/home/0/f003xn0/.conda/envs/pepatac/bin/refgenie", line 8, in <module>
    sys.exit(main())
  File "/dartfs-hpc/rc/home/0/f003xn0/.conda/envs/pepatac/lib/python3.9/site-packages/refgenie/cli.py", line 178, in main
    rgc.seek(
  File "/dartfs-hpc/rc/home/0/f003xn0/.conda/envs/pepatac/lib/python3.9/site-packages/refgenconf/refgenconf.py", line 736, in seek
    self._assert_gat_exists(genome_name, asset_name, tag_name)
  File "/dartfs-hpc/rc/home/0/f003xn0/.conda/envs/pepatac/lib/python3.9/site-packages/refgenconf/refgenconf.py", line 2765, in _assert_gat_exists
    raise MissingAssetError(
refgenconf.exceptions.MissingAssetError: Genome 'rCRSd' exists, but asset 'bowtie2_index' is missing
```

Attached is the config file:
```
config_version: 0.4
genome_folder: /dartfs-hpc/rc/lab/W/WangX/Genomes_and_extra/refgenie
genome_servers: 
 - http://refgenomes.databio.org
genomes:
  94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4:
    aliases: 
     - rCRSd
```

The target folder has the following structure:
```
|-- alias
|   `-- rCRSd
|-- data
|   `-- 94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4
|       `-- bowtie2_index
`-- genome_config.yaml
```

I have also confirmed that the folder bowtie2 is there, but is completely empty. The same occurs after pulling any other asset. Thank you in advance for your help

**Comment by nsheff** [comment]
Your download didn't complete... so probably need to re-download it.

the partial writing issue is a problem with refgenie, that it doesn't wait for it to finish before starting to write, so you're ending up with a partly finished process.

This will be prevented in the new coming refgenie1 release
