### ISSUE TITLE
refgenie is incompatible with Python 3.10 and above

### ISSUE THREAD

**Issue by lparsons** [refgenie/refgenie#279]
Attempting to use `refgenie` with Python 3.10 and above results in at least the following error:

Command:
```bash
refgenie upgrade --target-version 0.4
```
Result:
```python
Traceback (most recent call last):
  File "/Genomics/argo/users/lparsons/mambaforge/envs/refgenie/bin/refgenie", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Genomics/argo/users/lparsons/mambaforge/envs/refgenie/lib/python3.12/site-packages/refgenie/cli.py", line 416, in main
    upgrade_config(
  File "/Genomics/argo/users/lparsons/mambaforge/envs/refgenie/lib/python3.12/site-packages/refgenconf/refgenconf.py", line 2875, in upgrade_config
    from .refgenconf_v03 import _RefGenConfV03 as OldRefGenConf
  File "/Genomics/argo/users/lparsons/mambaforge/envs/refgenie/lib/python3.12/site-packages/refgenconf/refgenconf_v03.py", line 12, in <module>
    from collections import Iterable, Mapping, OrderedDict
ImportError: cannot import name 'Iterable' from 'collections' (/Genomics/argo/users/lparsons/mambaforge/envs/refgenie/lib/python3.12/collections/__init__.py)
```

**Comment by nsheff** [comment]
FIXED in refgenconf 0.12.3.
