### ISSUE TITLE
Upgrading configuration from 0.3 to 0.4 fails

### ISSUE THREAD

**Issue by lparsons** [refgenie/refgenie#281]
Attempting to upgrade my configuration from 0.3 to 0.4 fails with following error:

```
Upgrading config to v0.4. Current genome identifiers will be replaced with sequence-derived digests and contents of '/Genomics/biocomp/refgenie-genomes/genomes' will be moved to 'data' and 'alias' directories. For more info visit: http://refgenie.databio.org/en/latest/upgrade_config/. Would you like to proceed? [y/N] y
```
```python
/Genomics/argo/users/lparsons/mambaforge/envs/refgenie/lib/python3.9/site-packages/refgenconf/refgenconf_v03.py:533: RuntimeWarning: Could not find the 'default_tag' key for asset 'hg38/fasta'. Returning 'default' instead. Make sure it does not corrupt your workflow.
  warnings.warn(
Traceback (most recent call last):
  File "/Genomics/argo/users/lparsons/mambaforge/envs/refgenie/lib/python3.9/site-packages/attmap/ordattmap.py", line 46, in __getitem__
    return super(OrdAttMap, self).__getitem__(item)
KeyError: 'seek_keys'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Genomics/argo/users/lparsons/mambaforge/envs/refgenie/lib/python3.9/site-packages/refgenconf/refgenconf_v03.py", line 1867, in _assert_gat_exists
    tag_data[CFG_SEEK_KEYS_KEY]
  File "/Genomics/argo/users/lparsons/mambaforge/envs/refgenie/lib/python3.9/site-packages/attmap/pathex_attmap.py", line 59, in __getitem__
    v = super(PathExAttMap, self).__getitem__(item)
  File "/Genomics/argo/users/lparsons/mambaforge/envs/refgenie/lib/python3.9/site-packages/attmap/ordattmap.py", line 48, in __getitem__
    return AttMap.__getitem__(self, item)
  File "/Genomics/argo/users/lparsons/mambaforge/envs/refgenie/lib/python3.9/site-packages/attmap/attmap.py", line 32, in __getitem__
    return self.__dict__[item]
KeyError: 'seek_keys'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Genomics/argo/users/lparsons/mambaforge/envs/refgenie/bin/refgenie", line 10, in <module>
    sys.exit(main())
  File "/Genomics/argo/users/lparsons/mambaforge/envs/refgenie/lib/python3.9/site-packages/refgenie/cli.py", line 416, in main
    upgrade_config(
  File "/Genomics/argo/users/lparsons/mambaforge/envs/refgenie/lib/python3.9/site-packages/refgenconf/refgenconf.py", line 2928, in upgrade_config
    asset_path = rgc.seek(genome, "fasta", tag, "fasta")
  File "/Genomics/argo/users/lparsons/mambaforge/envs/refgenie/lib/python3.9/site-packages/refgenconf/refgenconf_v03.py", line 419, in seek
    path_val = _genome_asset_path(
  File "/Genomics/argo/users/lparsons/mambaforge/envs/refgenie/lib/python3.9/site-packages/refgenconf/refgenconf_v03.py", line 1795, in _genome_asset_path
    _assert_gat_exists(genomes, gname, aname, tname)
  File "/Genomics/argo/users/lparsons/mambaforge/envs/refgenie/lib/python3.9/site-packages/refgenconf/refgenconf_v03.py", line 1870, in _assert_gat_exists
    raise MissingSeekKeyError(
refgenconf.exceptions.MissingSeekKeyError: Asset incomplete. No seek keys are defined for 'hg38/fasta:default'. Build or pull the asset again.
```

The config file is:
```
config_version: 0.3
genome_folder: /Genomics/biocomp/refgenie-genomes/genomes
genome_servers: ['http://refgenomes.databio.org']
genomes:
  hg38:
    assets:
      fasta:
        tags:
          default:
            asset_digest: 59fed5ec3c3a95bc5709b24b8f2cf7bf
            asset_children: ['hg38/star_index:default']
      star_index:
        tags:
          default:
            seek_keys:
              star_index: .
            asset_parents: ['hg38/fasta:default']
            asset_path: star_index
            asset_digest: 528651b0b2477b5aba59da21c35fa75f
        default_tag: default
      ensembl_gtf:
        tags:
          default:
            seek_keys:
              ensembl_gtf: hg38.gtf.gz
              ensembl_tss: hg38_ensembl_TSS.bed
              ensembl_gene_body: hg38_ensembl_gene_body.bed
            asset_parents: []
            asset_path: ensembl_gtf
            asset_digest: 247fa6fbf98ce6b5773cbed0bdd86fef
        default_tag: default
    genome_description: The GCA_000001405.15 GRCh38_no_alt_analysis_set from NCBI
    genome_digest: b3422045db2293738bcb9973c1a0acdfabff3a0a3e1830bc
```

**Comment by nsheff** [comment]
This issue has been fixed in refgenie 0.13
